# Tasks to install zabbix-agent on CentOS

- name: check zabbix repo is installed
  stat:
    path: /etc/yum.repos.d/zabbix.repo
  register: zabbix_repo_result
      
- name: Install zabibx repository
# rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
  dnf:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present
  when: not zabbix_repo_result.stat.exists
  notify: dnf_clean_metadata
  



- name: Install zabbix-agent
  dnf:
    name: zabbix-agent
    state: present


- name: Start zabbix agent process
  service:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Customized zabbix agent configuration file
  template:
    src: zabbix_agentd.conf.j2
    dest: "{{ zabbix_agentd_conf }}"    
  notify: Restart zabbix-agentd    