- name:  Install PGP key for passenger
  shell: apt-key adv --keyserver {{ passenger_gpg_key_server }} --recv-keys {{ passenger_gpg_key }}

- name:  Add apt repository for passenger
  template:
    src: passenger.list.j2
    dest: /etc/apt/sources.list.d/passenger.list
- name: Run apt update
  apt:
    update_cache: yes


- name: Rails | Install ruby dependencies
  apt:
    update_cache: yes
    name: [ gcc
    , autoconf
    , bison
    , build-essential
    , libssl-dev
    , libyaml-dev
    , libreadline6-dev
    , zlib1g-dev
    , libncurses5-dev
    , libffi-dev
    , libgdbm-dev
    , nodejs
    , curl
    , gnupg
    , dirmngr
    , apt-transport-https
    , ca-certificates
    , libapache2-mod-passenger
    ]
    state: present


  

    

- name: Rails | Create a symbol link for nodejs
  file:
    src: "/usr/bin/nodejs"
    dest: "/usr/local/bin/node"
    state: link

- name: Rails | Enable Passenger module
  shell: a2enmod passenger
  notify: restart apache2

- name: Validate passenger installation
  shell: /usr/bin/passenger-config validate-install --auto
 


