---

- name: At first, Update cache
  dnf:
    update_cache: yes

- name: Apache | Install apache 
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ httpd_packages }}"

- name: Customized httpd.conf file
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '0644'
- name: Ensure required direcotry exists
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items: 
    - /etc/httpd/sites-available
    - /etc/httpd/sites-enabled

  
- name: Ensure httpd is runing
  service:
    name: httpd
    state: started
    enabled: true
    






