- name: Include playbook for ubuntu
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Include playbook for CentOS 8
  include: centos.yml
  when: ansible_distribution == "CentOS"