---
- name: Apache | Install apache 
  apt:
    name=apache2
    update_cache=yes
    state=latest


- name: Enable mod_rewrite
  apache2_module: 
    name=rewrite
    state=present
  notify: restart apache2
  

    







