- name: Install python3 mysql libraries
  apt: 
    name=python3-mysqldb 
    state=present

- name: MySQL | Install mysql package
  apt: 
    name: ['mysql-common', 'mysql-server-{{ mysql_version}}', 'mysql-client-{{ mysql_version }}']
    state: present
  become: true
 

- name: MySQL | create MySQL Configration file
  template:
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
    backup=yes
    owner=root
    group=root
    mode=0644
  become: true

- name: MySQL | create MySQLD configuration file
  template:
    src=mysqld.cnf.j2
    dest=/etc/mysql/conf.d/mysqld.cnf
    backup=yes
    owner=root
    group=root
    mode=0644
  become: true
  notify:
    - restart mysql
# - name: MySQL | Set root password
#   mysql_user:
#     name=root
#     host=localhost
#     password={{mysql_root_password}}
#   become: true
  
- name: MySQL | Delete anonymous user for localhost
  mysql_user:
    name=""
    state="absent"
    host=localhost
    login_user=root
    login_password={{mysql_root_password}}
- name: MySQL | Secure root user for localhost
  mysql_user:
    name="root"
    password="{{mysql_root_password}}"  
    host="localhost"
    login_user=root
    login_password={{mysql_root_password}} 
- name: MySQL | Create application Database
  mysql_db:
    db={{application_db}}
    state=present
    login_user=root
    login_password={{mysql_root_password}}
  

- name: MySQL | Create application database user
  mysql_user:
    name={{dbuser}}
    password={{dbpass}}
    priv=*.*:ALL
    host='localhost'
    state=present
    login_user=root
    login_password={{mysql_root_password}}
  notify:
    - restart mysql