
---
- name: Check if mysql is already installed
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Install python3 mysql libraries
  apt: 
    name: python3-mysqldb 
    state: present
- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Ensuer pymysql is present
  pip:
    name: pymysql
    state: present
- debug:
    msg: "The following pacakges will be installed {{ mysql_packages | list }}"
    
- name: MySQL | Install mysql package
  apt: 
    name: "{{ mysql_packages | list }}"
    state: present
  
# - name: MySQL | Delete anonymous user for localhost
#   mysql_user:
#     name=""
#     state="absent"
#     host=localhost
#     login_user=root
#     login_password={{mysql_root_password}}

 # 默认刚安装mysql，root 用户使用auth_socket
- name: MySQL | Secure root user for localhost and set root password
  mysql_user:
    name="root"
    password="{{mysql_root_password | mandatory}}"  
    host="localhost"
    login_unix_socket='/var/run/mysqld/mysqld.sock' 
    state=present
  become: yes
  when: not mysql_installed.stat.exists

- name: MySQL | Create application Database
  mysql_db:
    db: "{{application_db}}"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
  when: not mysql_installed.stat.exists

  

- name: MySQL | Create application database user
  mysql_user:
    name={{dbuser}}
    password={{dbpass}}
    priv={{application_db}}.*:ALL
    host='localhost'
    state=present
    login_user=root
    login_password={{mysql_root_password}}
  when: not mysql_installed.stat.exists
  notify:
    - restart mysql