---
# Load tasks according to linux distribution
- include_tasks: {{ ansible_facts['distribution'] }}.yml

- name: Create a directory if not exists
  file:
    path: {{log_file_dir }}
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'
- name: Ensure zabbix-agent started
  service:
    name: zabbix-agent
    state: started
    enabled: yes
    
- name: Copy file to remote host
  template:
    src: zabbix_agentd.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  handler: Restart zabbix-agentd
  