---
- name: Enable remi repo for php 7.2
  set_fact: php_enablerepo="remi,remi-php72"
  when:  php_version  == 7.2

- name: Enable remi repo for php 7.3
  set_fact: php_enablerepo="remi,remi-php73"
  when:  php_version == 7.3

- name: Enable remi repo for php 7.4
  set_fact: php_enablerepo="remi,remi-php74"
  when:  php_version == 7.4



- name: Install and enable php modules  
  block:
    - name: Import remi GPG Key
      rpm_key:
        key: "{{ remi_repo_gpg_key_url }}"
        state: present
    

    - name: Ensure dnf-plugins are installed on CentOS 8+ 
      yum:
        name: dnf-plugins-core
        state: present
    - name:  install the Remi repository configuration package
      dnf: 
        name:  " {{ remi_repo_url }}"
        state: present 

    - name: Install php module
      shell: |
        dnf module reset php -y
        dnf module install php:remi-{{ php_version }} -y
      args:
        warn: false  

    - name: Enable module for CentOS 8+
      shell: dnf module enable -y php:remi-{{ php_version }}
      args:
        warn: false
      register: dnf_module_enable
      changed_when: "'Nothing to do' not in dnf_module_enable.stdout"

    - name: Install php and required modules
      package:
        name:  "{{ php_packages }}"
        state: present
  when:
    - ansible_facts['distribution'] == 'CentOS' 


