---

- name: Ensure redis is installed
  package:
    name: redis
    state: present
    
- name: Enable redis start on boot
  service: 
    name: redis
    state: started
    enabled: yes
# Include linux distributon specicific tasks
- include_tasks: {{ ansible_facts['distribution'] }}.yml